### ISSUE TITLE
Support for Nanoleaf Canvas ( switch on and off ) 

### ISSUE THREAD

**Issue by TonKkkkk** [morrijr/node-red-contrib-nanoleaf-aurora#3]
The switching off ( and on ) of the "new" Canvas panels does not work.
To solve this I added _`operation = {"value":true};`_ and _`operation = {"value":false};`_ to the power.js file as described in the API documentation. ( http://forum.nanoleaf.me/docs/openapi §5.3.1 )

**Comment by morrijr** [comment]
Hi, thanks for the bug report. I've not got a canvas so I've been unable to check, but you are perfectly correct as far as the API goes. Perhaps they've gotten stricter?

Anyway, I've patched the files, just going to ensure that my Auroras work and I'll push the change ASAP.

Thanks again for taking the time to report the issue (having to create a github account and everything!), it really is appreciated.

**Comment by morrijr** [comment]
Pushed version 0.1.1 to npm. It takes a little while for Node-Red to detect the package changes sometimes, best give it a few hours.

**Comment by TonKkkkk** [comment]
Thank you also for your quick response :-)
Was a bit of a search and experiment to get this on of thing to work, so am happy to save others this effort.
If I read following post on the nanoleaf forum, https://forum.nanoleaf.me/forum/aurora-open-api/difference-between-canvas-and-aurora-api,  I am not sure if they got stricter or finding there "merge" problems between the Aurora and Canvas branch...

**Comment by morrijr** [comment]
Well spotted. If there's anything else not working/you need for the Canvas, please do reach out.

**Comment by TonKkkkk** [comment]
Updated to your version, works like a charm (for the moment ;-) )
