### ISSUE TITLE
Integration with docker

### ISSUE THREAD

**Issue by bplatypus** [morrijr/node-red-contrib-nanoleaf-aurora#5]
Hi,
Thanks for this lib! I tried it without success but my node-red is running on docker.
Did you try it on docker?
Maybe I have to add --net=host to the docker run command... didn't try it yet.

**Comment by morrijr** [comment]
Hi,

My node-red installation is running on a Synology NAS under its docker support. I suspect that the container is unable to reach out to the network that you're using to host your nanoleafs?

But I can assure you that it can and does work on a docker installation :)

**Comment by bplatypus** [comment]
It's working, but the --net=host is required! Thanks.
